config/routes.rb
Rails.application.routes.draw do
  resources :transactions, controller: "transactions"
  resource :sessions, controller: "sessions"
  resources :users, controller: "users"
  resources :individuals, controller: "individuals"
  resources :companies, controller: "companies"
  resources :updates, controller: "updates"
  resources :fundings, controller: "fundings"
  resources :comments, controller: "comments"
  resources :companies, controller: "companies"
  resources :projects, controller: "projects"
  resources :projects do
    collection do
      post :email
    end
  end
  resources :projects do
    collection do
      post :search
    end
  end
  root 'home#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
	mount_uploaders :images, ProjectUploader
	acts_as_taggable
	searchkick
	belongs_to :individual
	belongs_to :company
	has_many :comments, foreign_key: :project_id
	has_many :fundings, foreign_key: :project_id
	after_save :reset_amount
	
	def reset_amount
		res = 0
		self.fundings.each do |fund|
			res+=fund.amount
		end
		self.total_amount = res
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def search
    @projects = Project.search params[:search][:search], match: :phrase
    render :index
  end

  # def email
  #   project =Project.find(params[:id])
  #   case project.user_type
  #   when 1
  #     user = Individual.find(project.user_id)
  #   when 2
  #     user = Company.find(project.user_id)
  #   end
  #   AppMailingJob.perform_later(user.email,params[:msg])
  #   redirect_to request.referer
  # end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      redirect_to new_projects_path
    end
  end

  def edit
    @project = Project.find(:project_id)
  end

  def update
    @project = Project.find(params[:project_id])
    if @project.update(project_params)
      redirect_to projects_path(@project.id)
    else
      redirect_to edit_projects_path
    end
  end

  def show
    @project = Project.find(params[:id])
    @link = @project.youtubelink.match(/=(.+)/).captures.first
    #this is real implementation
    # case @project.user_type
    # when 1
    #   @user = Individual.find(@project.user_id)
    # when 2
    #   @user = Company.find(@project.user_id)
    # end
    @user = Individual.find(@project.user_id)

    # @time = (@project.time-(@project.created_at-Time.now).to_i).round

  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
  end

  def index
      @projects = Project.all
  end

  def project_params
    params.require(:project).permit(:time,:title,:subtitle,:user_id,:required_talents,:goal,:total_amount,:description,{images:[]}, :youtubelink)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<div class="container">
	
		<div class="form-group">
			<label for="field_1">Project Title</label>
			<div class="textfield" style="width:50%">
				<%= f.text_field :title, class: "form-control" %>
			</div>
		</div>

		<div class="form-group">
			<label for="field_1">Project Subtitle</label>
			<div class="textfield" style="width:50%">
				<%= f.text_field :subtitle, class: "form-control" %>
			</div>
		</div>

		<div class="form-group">
			<label for="field_2">Pledge a Goal</label>
			<div class="textfield" style="width:50%">
				<%= f.text_field :goal, class: "form-control", placeholder: "Amount of fundings required in RM" %>
			</div>
		</div>

		<div class="form-group">
			<label for="field_1">Length of Campaign</label>
			<div class="textfield" style="width:50%">
				<%= f.text_field :time, class: "form-control", placeholder: "Number of Days" %>
			</div>
		</div>

		<div class="form-group">
			<label for="field_1">Project Description</label>
			<div class="textfield" style="width:50%">
				<%= f.text_area :description, class: "form-control", placeholder: "Describe your project" %>
			</div>
		</div>

		<div class="form-group">
			<label for="field_1">Video Link</label>
			<div class="textfield" style="width:50%">
				<!-- <input type="text" name="dummy" class= "form-control" placeholder="Put your link here" /> -->
				<%= f.text_field :youtubelink, class: "form-control", placeholder: "Put your link here" %>
			</div>
		</div>

		<div class="form-group">
			<label for="field_1">Talents Required</label>
			<div class="textfield" style="width:50%">
				<input type="text" name="dummy" class= "form-control" placeholder="List down the talents required eg. Ruby Developer" />
				<%#= f.text_field :description, class: "form-control", placeholder: "Talents" %>
			</div>
		</div>

		<div class="form-group">
			<label for="field_1">Project Images</label>
			<div>
				<%= f.file_field :images, multiple: true %>
			</div>
		</div>
		
		<%= f.hidden_field :user_id, value:"#{session[:user_id]}" %>
	  
		<div class="form-group">
			<div>
				<%= f.submit 'Create Project!', class: 'btn btn-primary btn-lg' %>
			</div>
		</div>
<% end %>
</div>

app/views/projects/index.html.erb
<br>
<br>
<div class="container">
<% @projects.each do |proj| %>
  	<!-- Portfolio Item Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= proj.title %>
          <small><%= proj.subtitle %></small>
        </h1>
      </div>
    </div>
    <!-- /.row -->
    <!-- Portfolio Item Row -->
    <div class="row" id="project-bckg">
      <div class="col-md-8">
        <%= image_tag(proj.images.first, size: '600x280') %>
      </div>
      <div class="col-md-4">
        <h3>Project Description</h3>
        <p><%= proj.description %></p>
        <% if session[:user_id].nil? %>
          <%= link_to 'Project Details', '#', class: 'btn btn-primary', data: {toggle: "modal", target: "#myModal"}  %>
        <% else %>
          <%= link_to 'Project Details', proj, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <%= render partial: '/sessions/form' %>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<br>
<br>
<br>
<h1 align="center">CREATE A NEW PROJECT!</h1>
<%= render 'form' %>
<br>

app/views/projects/show.html.erb
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    /*footer {
      background-color: black;
      color: black;
      padding: 15px;
    }*/
    
    .left {
    float: left;
		}
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;}
    }

    .container-flex {
    max-width: 1040px;
    margin-right: auto;
    margin-left: auto;
		}

		.video1 {
			padding: 20px 10px 20px;
		}
		
		.projects_hero {
			max-height: 345px;
		}

		.bold {
    font-weight: bold;
		}
		
		@media (min-width: 640px)
		h1, .h1 {
		    font-size: 48px;
		    line-height: 50px;
		}

		.text {
    font-weight: 500;
    color: #80809E;
    font-size: 15px; 
  	}


		.h1, h1 {
			font-size: 36px;
		}
		
		.h1, .h2, .h3, h1, h2, h3 {
			margin-top: 20px;
			margin-bottom: 0px;
		}

		.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
			font-family: inherit;
			line-height: 1.1;
			font-weight: 550;
			color: inherit;
		}

		.btn[class*="btn--"] {
    	font-weight: bold;
		}

		.btn--large {
	    font-size: 16px;
	    padding: 18px 30px;
		}
		
		.btn--green, .btn--like.btn--liked {
	    background-color: #2BDE73;
	    color: #FFFFFF;
		}
		
		.btn {
	    transition: all 0.2s ease-in-out;
	    border-width: 2px;
	    border-color: transparent;
	    border-style: solid;
	    border-radius: 6px;
	    cursor: pointer;
	    display: inline-block;
	    font-family: "Helvetica Neue", Helvetica, Arial, "Liberation Sans", FreeSans, sans-serif;
	    line-height: 1;
	    text-align: center;
		}

		a, a:link a:visited, a:active, button, button:visited, button:active {
	    color: #2752ff;
	    text-decoration: none;
		}

		.button-space {
			padding-top: 30px;
    	padding-bottom: 34px;
		}

		.NS_projects__category_location.ratio-16-9 {
    margin-bottom: 15px;}

		.NS_projects__category_location a {
		    color: #80809E;
		    margin-right: 20px;
		}

		.col-right {
    		float: right;
		}
		
		.col, .col-right, .col-center, .mobile-col, .px-gutter {
		    box-sizing: border-box;
		    padding-left: 20px;
		}
		.align-right {
    	text-align: right;
		}

		.projects-2 {
			background-color: #e5e5ea;
		}

		.col-sm-3{
	  		padding-top: 10px;
    		margin-top: 40px;
  		}

		.caption-1 {
		  overflow: hidden;  
		}

  	.thumbnail {
	    display: block;
	    padding: 10px;
	    margin-bottom: 20px;
	    line-height: 1.42857143;
	    background-color: #fff;
	    border: 1px solid #ddd;
	    border-radius: 4px;
	    margin-top: 20px;
	    -webkit-transition: border .2s ease-in-out;
	    -o-transition: border .2s ease-in-out;
	    transition: border .2s ease-in-out;
		}

		.endorse{
	    padding-left: 50px;
	    padding-top: 10px;
		}

		.endorse-text{
			color: #80809E;
		}

		hr #divide1{
			color: #FFFFFF;
		}

		hr {
	    margin-top: 20px;
	    margin-bottom: 20px;
	    border: 0;
	    border-top: 1px solid #eee;
  		}



	  .alert {
	    padding: 15px;
	    margin-bottom: 20px;
	    border: 1px solid transparent;
	    border-radius: 4px;
	    text-align: center;
		}

	  	#h4skills{
	  		margin-top: 100px;
	  	}

	  	.remote_modal_dialog{
	  		padding-right: 70px;
	  	}


  </style>

<br>
<br>
<br>

<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<section class="projects_hero">
<div class="projects-2">
	<div class="container-flex px2">
		<div class="col-sm-8 left video1">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/<%=@link%>" frameborder="0" allowfullscreen></iframe>
			<div class="mobile-hide">
				<div class="NS_projects__category_location ratio-16-9">
					<a class="grey-dark mr2 nowrap" href="/discover/places/washington-dc?ref=city"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
						Washington, DC
					</a>
					<a class="grey-dark mr2 nowrap" href="/discover/categories/film%20&amp;%20video/documentary?ref=category"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
						Documentary
					</a>
					<h2><%= @project.title %></h2>
				</div>
			</div>
		</div>
	</div>

	<div class="col-sm-4">
		<div class="col col-12 mb1 stat-item">
			<div class="num h1 bold" id="backers_count"><data class="Project1997781445" data-format="number" data-value="0" itemprop="Project[backers_count]">
			<%= @project.backers %>
			</data></div>
			<span class="text">backers</span>
		</div>

		<div class="col col-12 mb1 stat-item">
			<div class="num h1 bold nowrap" data-goal="100000.0" data-percent-raised="1.13847" data-pledged="113847.0" data-ref-tag="hero" id="pledged">
				<data class="Project1997781445" data-currency="USD" data-format="shorter_money" data-precision="0" data-value="113905.0" itemprop="Project[pledged]">RM<%= @project.total_amount %></data>
				<span class="money usd project_currency_code"></span>
			</div>
				<span class="text">pledged of RM<%= @project.goal %> goal</span>
			</div>

		<div class="col col-12 stat-item">
			<div class="ksr_page_timer poll stat" data-dynamic="5" data-end-time="2016-08-05T23:59:00-04:00">
				<div class="num h1 bold"><%= @project.time %></div>
				<span class="text">hours to go</span>
				</div>
		</div>

		<div class="col col-12 button-space">
			<button class="btn btn--green btn--large" id="button-back-this-proj" data-toggle="modal" data-target="#funding" title="Back this project">Fund This Project</a>
		</div>
		<div class="modal fade" id="funding" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="myModalLabel">How much would you like to fund?</h4>
		      </div>
		      <div class="modal-body">
		        <%= form_for :fund, url: fundings_path do |f| %> 
		        	<h4>Email: <%= f.text_field :email %></h4>
		        	<h4>Amount: RM<%= f.text_field :amount %></h4>
		        	<%= f.hidden_field :user_id, value:current_consumer.id%>
		        	<%= f.hidden_field :project_id, value: @project.id %>
		        	<button class="btn btn--green btn--small"<%= f.submit %>Fund
				<% end %>
				</div>
		    </div>
		  </div>
		</div>


		<div class="col-right col-4">

		<div class="mobile-hide"><a class="remote_modal_dialog" data-modal-class="modal_project_by" data-modal-title="About the creator" href="/individuals/<%=@user.id%>"><%= image_tag(@user.images.first.thumb, class: "img-circle img-center") if @user.images? %></a></div>

		</div>


		<div class="col col-8">
			
			<div class="mobile-show center py1">
				<h5 class="mb1">Project by </h5><h3 class="normal mb0"><a class="green-dark" href="/projects/ladiesnightanthology/ladies-night-anthology-vol-4-eat-it-up/creator_bio"></a></h3>
			</div>
			<div class="flag mobile-hide">
				<p class="h5 mb0">
					<span class="inline-block">
					<span class="grey-dark"><%= @user.name%></span>
					<span class="grey-dark">&nbsp;|&nbsp;</span>
					</span>
					<span class="inline-block">
					<span class="grey-dark"><%= @user.occupation%></span>
					</span>
				</p>
			</div>
			<p class="h5 bold mobile-hide">
			<a class="remote_modal_dialog full_bio mr2" data-modal-class="modal_project_by" data-modal-title="About the creator" href="/projects/ladiesnightanthology/ladies-night-anthology-vol-4-eat-it-up/creator_bio">See full bio</a>

			</p>
			</div>
	</div>
			<hr>
			</div>
</section>
<br><br>

<section class="projects_description">
<div class="container-flex px2">
<div class="col-sm-8 left" style="width: 70%;">
      <h4><small>ABOUT THIS PROJECT</small></h4>
      <hr>
      <h2><%= @project.subtitle %></h2>
      <h5><span class="glyphicon glyphicon-time"></span> Posted on, <%= @project.created_at.month %> <%= @project.created_at.day%>, <%= @project.created_at.year%>.</h5>
      <h5><span class="label label-danger">Science</span> <span class="label label-primary">Tech</span></h5><br>
      <p><%= @project.description %></p>
      <br><br>

			    	
			    
		 <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		  <ol class="carousel-indicators">

		  	<% @project.images.each_with_index do |x, index| %>
		    	<li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="<%= "active" if index == 0 %>"></li>
		    <% end %>
		  </ol>
		  <div class="carousel-inner" role="listbox">

		  	<% @project.images.each_with_index do |x, index| %>
			    <div class="item <%= "active" if index == 0 %>">
			      <img src=<%= x.url %> alt="<%= x.url %>" style="width: 100%;">
			    </div>
		    <% end %>
		  </div>
		  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		    <span class="icon-prev" aria-hidden="true"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		    <span class="icon-next" aria-hidden="true"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>


      
      <h4>Leave a Comment:</h4>
      <%= form_for :com, url: comments_path, html: {role:"form", id:"comment"} do |f|%>
			<%= f.hidden_field :user_id, value:current_consumer.id%>
		    <%= f.hidden_field :project_id, value:1%>
		    <%= f.hidden_field :type, value:session[:type]%>
        <div class="form-group">
          <%= text_area(:com, :comment, rows: 3,required: true, class: "form-control") %>
        </div>
        <%= f.submit 'Submit'%>
      <% end %>
      <br><br>
      
      <p>Comments:</p><br>
      <div id='comment_block'>
      <% @project.comments.each do |com|%>
      	<div class="col-sm-10">
      		<p><%=com.comment%></p>
      	</div>
      <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</section>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>Endorsed By</h4>
        <div class="col-sm-6">

	        <a href="/companies/show">
				<img src="https://images-na.ssl-images-amazon.com/images/I/515xJHzhyPL.jpg" style="width:100px;height:100px;border:0;">
			</a>
		</div>
		<div class="col-sm-6">
			<a href="/companies/new">
				<img src="http://www.ucarecdn.com/d7b2c770-8942-44ca-aa10-6c81c66d7675/-/preview/300x300/" style="width:100px;height:100px;border:0;">
			</a>
        </div>
       
        <hr id="divide1">
        <h4 id="h4skills">Skills In-need</h4>
        <div class="thumbnail skills">
          <img src="http://oakwoodprimary.co.uk/wp-content/uploads/2014/01/vacancies2__large.jpg" alt="">
          <div class="caption-1">
              <h3><%=@project.required_talents%> Ruby Developer Needed!</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
              <p>
                    <button class="btn btn-primary" data-toggle="modal" data-target="#applyModal">Apply Now!</button> <a href="#" class="btn btn-default">More Info</a>
              </p>
          </div>
      	</div>
        
    </div>
</div>
</div>

<div class="modal fade" id="applyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="myModalLabel">Apply For : Ruby Developer</h4>
		      </div>
		      <div class="modal-body">
		        <%= form_for :mail, url:email_projects_path do |f|%>
				  <div class="form-group">
				    <label for="exampleInputEmail1">Email address</label>
				    <%= f.email_field :email, html:{class:"form-control", id:"exampleInputEmail1", placeholder:"Email"}%>
				  </div>
				  <div class="form-group">
				    <label for="message">Message</label>
				    <%= f.text_field :message, html:{class:"form-control", id:"message", placeholder:"Few words about yourself"}%>
				  </div>
				  <div class="form-group">				   
				    <p>Once submited, all your info will be send to the owner of this project</p>
				  </div>
				  <%=f.submit "Apply!"%>
				 <% end%>
				</form>
		      </div>
		    </div>
		  </div>
		</div>   