config/routes.rb
Rails.application.routes.draw do
  resources :transactions, controller: "transactions"
  resource :sessions, controller: "sessions"
  resources :users, controller: "users"
  resources :individuals, controller: "individuals"
  resources :companies, controller: "companies"
  resources :updates, controller: "updates"
  resources :fundings, controller: "fundings"
  resources :comments, controller: "comments"
  resources :companies, controller: "companies"
  resources :projects, controller: "projects"
  resources :projects do
    collection do
      post :email
    end
  end
  resources :projects do
    collection do
      post :search
    end
  end
  root 'home#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :individual
	belongs_to :company
	belongs_to :user
	belongs_to :project
end

app/models/company.rb
class Company < ActiveRecord::Base
	mount_uploaders :images, CompanyUploader
	has_secure_password
	has_many :fundings, foreign_key: :user_id
	has_many :projects, foreign_key: :user_id
	has_many :comments, foreign_key: :user_id
end

app/models/funding.rb
class Funding < ActiveRecord::Base
	belongs_to :individual
	belongs_to :company
	belongs_to :user
	belongs_to :project
end

app/models/individual.rb
class Individual < ActiveRecord::Base
	mount_uploaders :images, IndividualUploader
  	has_secure_password
 	has_many :fundings, foreign_key: :user_id
	has_many :projects, foreign_key: :user_id
	has_many :comments, foreign_key: :user_id
end

app/models/project.rb
class Project < ActiveRecord::Base
	mount_uploaders :images, ProjectUploader
	acts_as_taggable
	searchkick
	belongs_to :individual
	belongs_to :company
	has_many :comments, foreign_key: :project_id
	has_many :fundings, foreign_key: :project_id
	after_save :reset_amount
	
	def reset_amount
		res = 0
		self.fundings.each do |fund|
			res+=fund.amount
		end
		self.total_amount = res
	end
end

app/models/stranger.rb
class Stranger < ActiveRecord::Base
  has_many :fundings, foreign_key: :user_id
	has_many :projects, foreign_key: :user_id
	has_many :comments, foreign_key: :user_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to request.referer
  end

  def update
  	@comment = Comment.find(params[:comment_id])
  end

  def comment_params
#    params[:comment][:comment]=params[:comment][:comment][:msg]
    params[:com][:user_id]=params[:com][:user_id].to_i
    params[:com][:project_id]=params[:com][:project_id].to_i
    params[:com][:user_type]=params[:com][:user_type].to_i
  	params.require(:com).permit(:comment,:user_id,:user_type,:project_id)
  end
end

app/controllers/fundings_controller.rb
class FundingsController < ApplicationController
  def create
  	if funding_params[:user_id].nil?
  		@user = Stranger.create(funding_params[:email])
  	elsif session[:type].nil?
  		@user = Stranger.find(funding_params[:user_id])
  	elsif session[:type] == 1
  		@user = Individual.find(funding_params[:user_id])
  	elsif session[:type] == 2
  		@user = Company.find(funding_params[:user_id])
  	end
  	hash = funding_params.delete_if {|key,value| key=='email'}
    @funding = Funding.create(hash)
    redirect_to "/transactions/new?fund_id=#{@funding.id}"
  end

  def funding_params
  	params.require(:fund).permit(:email,:amount,:user_id,:user_type,:project_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@projects = Project.all.limit(4)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def search
    @projects = Project.search params[:search][:search], match: :phrase
    render :index
  end

  # def email
  #   project =Project.find(params[:id])
  #   case project.user_type
  #   when 1
  #     user = Individual.find(project.user_id)
  #   when 2
  #     user = Company.find(project.user_id)
  #   end
  #   AppMailingJob.perform_later(user.email,params[:msg])
  #   redirect_to request.referer
  # end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      redirect_to new_projects_path
    end
  end

  def edit
    @project = Project.find(:project_id)
  end

  def update
    @project = Project.find(params[:project_id])
    if @project.update(project_params)
      redirect_to projects_path(@project.id)
    else
      redirect_to edit_projects_path
    end
  end

  def show
    @project = Project.find(params[:id])
    @link = @project.youtubelink.match(/=(.+)/).captures.first
    #this is real implementation
    # case @project.user_type
    # when 1
    #   @user = Individual.find(@project.user_id)
    # when 2
    #   @user = Company.find(@project.user_id)
    # end
    @user = Individual.find(@project.user_id)

    # @time = (@project.time-(@project.created_at-Time.now).to_i).round

  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
  end

  def index
      @projects = Project.all
  end

  def project_params
    params.require(:project).permit(:time,:title,:subtitle,:user_id,:required_talents,:goal,:total_amount,:description,{images:[]}, :youtubelink)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	temp = params[:session]
		@individual = Individual.find_by(email:temp['email'])
    @company = Company.find_by(email:temp['email'])
    if !@individual.nil?
      session[:user_id] = @individual.id
      session[:type] = 1
      redirect_to root_path
    elsif !@company.nil?
      session[:user_id] = @company.id
      session[:type] = 2
    else
      redirect_to new_sessions_path
    end
  
  end

  def destroy
  	session.delete(:user_id)
  	redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_consumer
		if session[:user_id]
			case session[:type]
			when 1
				@current_consumer ||=Individual.find_by_id(session[:user_id])
			when 2
				@current_consumer ||=Company.find_by_id(session[:user_id])
			end
		end
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/fundings_helper.rb
module FundingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/individual_helper.rb
module IndividualHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/_footer.html.erb
<style>
    footer {
          background-color: black;
          color: black;
          padding: 15px;
    }
</style>

<footer>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted text-center">Copyright &copy; shem mandy shenyew 2016</p>
            </div>
        </div>   
</footer>

app/views/layouts/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <%= link_to 'HML', root_path, class:"navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href='/projects'>Projects</a></li>
        <% if session[:user_id].nil? %>
          <li><%= link_to 'Start a Project', '#', data: {toggle: "modal", target: "#myModal"}  %></li>
        <% else %>
          <li><%= link_to 'Start a Project', new_project_path %></li>
        <% end %>
      </ul>
      <%=form_for :search,url:search_projects_path, :html => { :class => "navbar-form navbar-left searchbar" } do |f| %>
        <div class="form-group">
          <div class="input-group">
            <%= f.text_field :search, class:"form-control", id:'search-input'%>
            <span class="input-group-addon"><a href="#" onclick="$(this).closest('form').submit()"><span class="glyphicon glyphicon-search"></span></a></span>
          </div>
        </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
      <% if session[:user_id].nil? %>
        <li><%= link_to 'Log In', '#', data: {toggle: "modal", target: "#myModal"}  %></li>
        <li><%= link_to 'Sign up', '#', data: {toggle: "modal", target: "#mySignupModal"}  %></li>
      <% else %>
        <% if session[:type] == 1 %>
          <li><%= link_to current_consumer.name.capitalize, individual_path(current_consumer.id),method: :get %></li>
        <% else %>
          <li><%= link_to current_consumer.name, company_path(current_consumer.id),method: :get %></li>
        <% end %>
        <li ><%= link_to 'Log Out',sessions_path,method: :delete %></li>
      <% end%>
      </ul>
    </div>
  </div>
</nav>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <%= render partial: '/sessions/form' %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="mySignupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
      </div>
      <div class="modal-body">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          As Individual
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <%= render partial: '/individuals/form' %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
         As a company
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <%= render partial: '/companies/form' %>
      </div>
    </div>
  </div>
</div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kickstarterclone</title>
    <%= csrf_meta_tags %>
    <%= include_gon %>
    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render partial: '/layouts/navigation'%>
    <%= yield %>
    <%= render partial: '/layouts/footer'%>
  </body>
</html>